In [1]:
import pandas as pd

# Merge excel files
path = "turismoestado.csv"

dataset_df = pd.read_csv(path)

dataset_df

,ano,totalnacional,aguascalientes,baja california,baja california sur,campeche,coahuila,colima,chiapas,chihuahua,...,quintana roo,san luis potosi,sinaloa,sonora,tabasco,tamaulipas,tlaxcala,veracruz,yucatan,zacatecas
0,2003,320817.877,3009.298,12204.779,5821.453,3540.521,4785.095,3225.666,6052.549,7612.652,...,32380.682,4706.504,7823.521,6902.357,5716.830,6559.963,2494.659,17981.905,4991.722,1986.709
1,2004,332481.375,2846.622,12381.124,7885.062,3353.797,5066.859,3185.748,6386.225,8531.909,...,35181.012,5763.839,7958.754,7407.234,5923.131,6831.824,2907.019,16649.322,5290.800,2078.808
2,2005,337861.348,2670.236,13254.712,11014.099,3517.394,5088.358,3370.707,6231.334,8293.606,...,32017.471,5302.651,9925.138,7766.069,5732.307,6499.536,2547.686,16003.211,5793.468,2303.492
3,2006,343231.522,2449.527,13115.948,13048.744,3540.237,5965.387,3498.966,4950.321,8912.666,...,31804.810,5246.736,10395.509,9329.852,6360.371,6619.897,2734.577,17191.663,5445.108,2404.632
4,2007,350260.505,2376.980,13091.387,15306.901,3436.569,5986.460,3180.688,6006.764,7609.848,...,41084.933,5506.387,10123.523,8619.016,5538.573,6701.126,1788.716,16060.765,5473.290,2388.085
5,2008,349724.847,2605.283,11072.794,13644.222,3418.067,6186.633,2869.044,6014.228,8932.106,...,44227.868,5960.915,10130.076,7458.026,5588.850,6978.607,1481.318,13827.448,5669.843,2415.604
6,2009,314846.534,2190.537,9984.990,13294.530,3641.034,5382.830,3074.594,5982.459,8063.444,...,37483.001,5154.130,9918.678,7231.783,5101.747,6387.353,1374.307,13439.748,4745.718,2375.150
7,2010,319526.714,2307.857,9735.826,13895.684,3708.478,5076.590,3081.683,5652.104,8084.042,...,43510.115,4501.921,9371.723,6926.270,5004.653,4856.793,1314.086,12790.663,4960.058,2416.801
8,2011,325321.844,2439.548,9929.754,14250.285,3834.313,5263.023,3179.156,5624.642,7724.338,...,45219.865,4721.922,9066.516,7455.681,5128.864,5613.150,1252.540,12377.503,5428.318,2048.780
9,2012,341158.208,2817.615,10206.564,15999.833,4123.956,5589.676,3222.677,5798.165,7301.801,...,50529.431,4777.003,8968.758,7908.348,5931.322,6097.053,1285.599,12858.147,5390.157,2156.416
10,2013,344770.830,2902.186,10893.632,15543.510,4254.560,5555.012,2873.769,5361.347,7298.381,...,52930.544,4673.879,8864.609,7449.531,5443.260,7483.509,1260.227,12725.118,5044.927,2136.028
11,2014,351884.865,3013.849,11263.834,14647.114,4821.917,4859.747,3391.065,5228.832,6506.445,...,56043.540,3955.152,9457.520,7403.306,5112.467,5955.847,1254.076,13758.600,5089.341,2196.989
12,2015,375439.181,3390.240,12024.583,17284.922,4434.030,5676.806,3212.563,6077.716,7980.328,...,60651.430,4935.355,10341.243,7863.344,5150.733,6445.791,1511.947,12283.502,5706.093,2484.285
13,2016,385030.662,3669.932,12641.127,18672.983,4174.454,6103.111,3365.592,5992.626,7914.189,...,62407.021,5468.285,10598.682,8288.629,4800.688,6760.155,1516.073,11050.755,5555.322,2614.324
14,2017,397041.682,3928.135,12643.593,20919.630,3920.209,6077.479,3643.079,5977.213,7702.155,...,64427.905,6042.984,11069.010,8599.101,4965.644,6561.370,1634.957,11043.539,5902.968,2657.271
15,2018,405695.181,4396.160,11137.582,23710.001,4106.851,6710.143,3353.747,5928.178,7850.709,...,66084.735,6258.018,10494.404,8604.950,5249.435,7325.560,1427.076,11470.447,5759.519,2747.637

In [2]:
#set ano as index and swap axes
dataset_df = dataset_df.set_index('ano')
dataset_df = dataset_df.swapaxes("index", "columns")

dataset_df.head()

ano,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
totalnacional,320817.877,332481.375,337861.348,343231.522,350260.505,349724.847,314846.534,319526.714,325321.844,341158.208,344770.830,351884.865,375439.181,385030.662,397041.682,405695.181
aguascalientes,3009.298,2846.622,2670.236,2449.527,2376.980,2605.283,2190.537,2307.857,2439.548,2817.615,2902.186,3013.849,3390.240,3669.932,3928.135,4396.160
baja california,12204.779,12381.124,13254.712,13115.948,13091.387,11072.794,9984.990,9735.826,9929.754,10206.564,10893.632,11263.834,12024.583,12641.127,12643.593,11137.582
baja california sur,5821.453,7885.062,11014.099,13048.744,15306.901,13644.222,13294.530,13895.684,14250.285,15999.833,15543.510,14647.114,17284.922,18672.983,20919.630,23710.001
campeche,3540.521,3353.797,3517.394,3540.237,3436.569,3418.067,3641.034,3708.478,3834.313,4123.956,4254.560,4821.917,4434.030,4174.454,3920.209,4106.851

In [3]:
#reset index and remove index name
dataset_df.reset_index(level=0, inplace=True)
dataset_df.columns.name = None

dataset_df.head()

,index,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,totalnacional,320817.877,332481.375,337861.348,343231.522,350260.505,349724.847,314846.534,319526.714,325321.844,341158.208,344770.830,351884.865,375439.181,385030.662,397041.682,405695.181
1,aguascalientes,3009.298,2846.622,2670.236,2449.527,2376.980,2605.283,2190.537,2307.857,2439.548,2817.615,2902.186,3013.849,3390.240,3669.932,3928.135,4396.160
2,baja california,12204.779,12381.124,13254.712,13115.948,13091.387,11072.794,9984.990,9735.826,9929.754,10206.564,10893.632,11263.834,12024.583,12641.127,12643.593,11137.582
3,baja california sur,5821.453,7885.062,11014.099,13048.744,15306.901,13644.222,13294.530,13895.684,14250.285,15999.833,15543.510,14647.114,17284.922,18672.983,20919.630,23710.001
4,campeche,3540.521,3353.797,3517.394,3540.237,3436.569,3418.067,3641.034,3708.478,3834.313,4123.956,4254.560,4821.917,4434.030,4174.454,3920.209,4106.851

In [4]:
#reset index again to get id and rename index to state and level_0 to id
dataset_df.reset_index(level=0, inplace=True)
dataset_df.rename(columns={'index': 'state', 'level_0': 'id'}, inplace=True)
dataset_df.head()

,id,state,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,0,totalnacional,320817.877,332481.375,337861.348,343231.522,350260.505,349724.847,314846.534,319526.714,325321.844,341158.208,344770.830,351884.865,375439.181,385030.662,397041.682,405695.181
1,1,aguascalientes,3009.298,2846.622,2670.236,2449.527,2376.980,2605.283,2190.537,2307.857,2439.548,2817.615,2902.186,3013.849,3390.240,3669.932,3928.135,4396.160
2,2,baja california,12204.779,12381.124,13254.712,13115.948,13091.387,11072.794,9984.990,9735.826,9929.754,10206.564,10893.632,11263.834,12024.583,12641.127,12643.593,11137.582
3,3,baja california sur,5821.453,7885.062,11014.099,13048.744,15306.901,13644.222,13294.530,13895.684,14250.285,15999.833,15543.510,14647.114,17284.922,18672.983,20919.630,23710.001
4,4,campeche,3540.521,3353.797,3517.394,3540.237,3436.569,3418.067,3641.034,3708.478,3834.313,4123.956,4254.560,4821.917,4434.030,4174.454,3920.209,4106.851

In [5]:
new_df = dataset_df.iloc[1:]

In [6]:
new_df.head()

,id,state,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1,1,aguascalientes,3009.298,2846.622,2670.236,2449.527,2376.980,2605.283,2190.537,2307.857,2439.548,2817.615,2902.186,3013.849,3390.240,3669.932,3928.135,4396.160
2,2,baja california,12204.779,12381.124,13254.712,13115.948,13091.387,11072.794,9984.990,9735.826,9929.754,10206.564,10893.632,11263.834,12024.583,12641.127,12643.593,11137.582
3,3,baja california sur,5821.453,7885.062,11014.099,13048.744,15306.901,13644.222,13294.530,13895.684,14250.285,15999.833,15543.510,14647.114,17284.922,18672.983,20919.630,23710.001
4,4,campeche,3540.521,3353.797,3517.394,3540.237,3436.569,3418.067,3641.034,3708.478,3834.313,4123.956,4254.560,4821.917,4434.030,4174.454,3920.209,4106.851
5,5,coahuila,4785.095,5066.859,5088.358,5965.387,5986.460,6186.633,5382.830,5076.590,5263.023,5589.676,5555.012,4859.747,5676.806,6103.111,6077.479,6710.143

In [7]:
new_df.sort_values(by=['state'], inplace=True)
new_df

C:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,id,state,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1,1,aguascalientes,3009.298,2846.622,2670.236,2449.527,2376.980,2605.283,2190.537,2307.857,2439.548,2817.615,2902.186,3013.849,3390.240,3669.932,3928.135,4396.160
2,2,baja california,12204.779,12381.124,13254.712,13115.948,13091.387,11072.794,9984.990,9735.826,9929.754,10206.564,10893.632,11263.834,12024.583,12641.127,12643.593,11137.582
3,3,baja california sur,5821.453,7885.062,11014.099,13048.744,15306.901,13644.222,13294.530,13895.684,14250.285,15999.833,15543.510,14647.114,17284.922,18672.983,20919.630,23710.001
4,4,campeche,3540.521,3353.797,3517.394,3540.237,3436.569,3418.067,3641.034,3708.478,3834.313,4123.956,4254.560,4821.917,4434.030,4174.454,3920.209,4106.851
7,7,chiapas,6052.549,6386.225,6231.334,4950.321,6006.764,6014.228,5982.459,5652.104,5624.642,5798.165,5361.347,5228.832,6077.716,5992.626,5977.213,5928.178
8,8,chihuahua,7612.652,8531.909,8293.606,8912.666,7609.848,8932.106,8063.444,8084.042,7724.338,7301.801,7298.381,6506.445,7980.328,7914.189,7702.155,7850.709
9,9,ciudad de mexico,60985.387,63419.472,63731.593,58169.971,56811.627,57284.316,48731.217,50686.539,53675.473,56257.256,53555.241,47248.377,52847.297,51743.994,50190.927,49267.264
5,5,coahuila,4785.095,5066.859,5088.358,5965.387,5986.460,6186.633,5382.830,5076.590,5263.023,5589.676,5555.012,4859.747,5676.806,6103.111,6077.479,6710.143
6,6,colima,3225.666,3185.748,3370.707,3498.966,3180.688,2869.044,3074.594,3081.683,3179.156,3222.677,2873.769,3391.065,3212.563,3365.592,3643.079,3353.747
10,10,durango,1962.652,1987.078,1982.342,2259.835,2236.939,2348.798,2320.742,2345.391,2173.036,2273.304,2088.836,2281.060,2430.076,2517.947,2561.084,2739.303
15,15,estado de mexico,18356.796,18073.754,17911.955,20479.487,22951.450,22932.405,19738.768,18544.260,20210.343,19844.652,18749.053,21273.834,18240.677,19557.847,20500.448,18985.857
11,11,guanajuato,9365.469,9274.084,9558.573,10029.810,9529.606,9229.498,8878.111,9332.835,9402.064,10362.758,10631.670,10835.898,11654.369,12317.274,13040.812,13334.502
13,13,guerrero,10441.662,13077.126,12579.139,12923.496,13733.286,14059.602,11869.067,12818.629,11162.587,11616.156,11368.497,12396.321,12928.744,13001.839,13590.524,15154.976
12,12,hidalgo,3582.343,3277.533,3115.424,2976.643,2946.893,2611.448,2108.660,2430.670,2851.879,3314.977,3399.248,3749.557,4358.911,4093.143,3939.656,4504.408
14,14,jalisco,23282.562,22163.198,23969.114,24658.656,24726.775,24842.627,23067.045,22724.650,23275.943,23997.350,25212.586,30059.885,28625.848,31007.461,32907.196,32924.853
16,16,michoacan,7477.540,7331.995,8951.234,7807.425,7415.091,7687.477,7648.239,7457.483,6745.784,6793.939,6363.175,6672.312,6158.453,6579.271,7218.142,7452.901
17,17,morelos,5545.121,5502.879,5178.247,6202.708,5568.332,5636.316,5063.571,4694.450,4429.124,4613.546,4724.162,4284.195,5175.928,5145.195,5362.678,6346.857
18,18,nayarit,7442.226,7734.155,9260.542,9977.811,7684.346,9330.366,8603.284,10144.167,9612.622,7516.852,9533.392,10369.598,13661.417,14519.415,15433.944,15443.417
19,19,nuevo leon,15772.058,15673.311,16271.320,16954.555,18567.970,17253.403,14558.709,13215.834,12515.142,14047.300,14763.572,16079.040,17424.305,18158.000,18574.956,19103.307
20,20,oaxaca,6352.153,6833.573,6843.696,6233.009,6323.959,6570.725,6597.347,6544.451,6843.724,6678.700,7206.284,7019.452,7730.045,7247.216,7787.547,8662.424
21,21,puebla,8037.292,7899.302,6506.905,6389.803,6274.178,6554.244,6298.040,6337.239,6562.144,7203.290,8389.824,9309.609,10057.675,9970.502,10339.914,11130.528
22,22,queretaro,4417.751,4604.826,4669.789,5153.362,5210.042,4902.690,4537.701,5054.769,5303.781,5675.607,6091.261,6346.086,6690.525,7577.610,7877.612,8029.432
23,23,quintana roo,32380.682,35181.012,32017.471,31804.810,41084.933,44227.868,37483.001,43510.115,45219.865,50529.431,52930.544,56043.540,60651.430,62407.021,64427.905,66084.735
24,24,san luis potosi,4706.504,5763.839,5302.651,5246.736,5506.387,5960.915,5154.130,4501.921,4721.922,4777.003,4673.879,3955.152,4935.355,5468.285,6042.984,6258.018
25,25,sinaloa,7823.521,7958.754,9925.138,10395.509,10123.523,10130.076,9918.678,9371.723,9066.516,8968.758,8864.609,9457.520,10341.243,10598.682,11069.010,10494.404
26,26,sonora,6902.357,7407.234,7766.069,9329.852,8619.016,7458.026,7231.783,6926.270,7455.681,7908.348,7449.531,7403.306,7863.344,8288.629,8599.101,8604.950
27,27,tabasco,5716.830,5923.131,5732.307,6360.371,5538.573,5588.850,5101.747,5004.653,5128.864,5931.322,5443.260,5112.467,5150.733,4800.688,4965.644,5249.435
28,28,tamaulipas,6559.963,6831.824,6499.536,6619.897,6701.126,6978.607,6387.353,4856.793,5613.150,6097.053,7483.509,5955.847,6445.791,6760.155,6561.370,7325.560
29,29,tlaxcala,2494.659,2907.019,2547.686,2734.577,1788.716,1481.318,1374.307,1314.086,1252.540,1285.599,1260.227,1254.076,1511.947,1516.073,1634.957,1427.076
30,30,veracruz,17981.905,16649.322,16003.211,17191.663,16060.765,13827.448,13439.748,12790.663,12377.503,12858.147,12725.118,13758.600,12283.502,11050.755,11043.539,11470.447
31,31,yucatan,4991.722,5290.800,5793.468,5445.108,5473.290,5669.843,4745.718,4960.058,5428.318,5390.157,5044.927,5089.341,5706.093,5555.322,5902.968,5759.519
32,32,zacatecas,1986.709,2078.808,2303.492,2404.632,2388.085,2415.604,2375.150,2416.801,2048.780,2156.416,2136.028,2196.989,2484.285,2614.324,2657.271,2747.637

In [8]:
#Add an id state
seq_s =[i+1 for i in range(32)]
new_df["id_state"]=seq_s
new_df

C:\anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,id,state,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,id_state
1,1,aguascalientes,3009.298,2846.622,2670.236,2449.527,2376.980,2605.283,2190.537,2307.857,2439.548,2817.615,2902.186,3013.849,3390.240,3669.932,3928.135,4396.160,1
2,2,baja california,12204.779,12381.124,13254.712,13115.948,13091.387,11072.794,9984.990,9735.826,9929.754,10206.564,10893.632,11263.834,12024.583,12641.127,12643.593,11137.582,2
3,3,baja california sur,5821.453,7885.062,11014.099,13048.744,15306.901,13644.222,13294.530,13895.684,14250.285,15999.833,15543.510,14647.114,17284.922,18672.983,20919.630,23710.001,3
4,4,campeche,3540.521,3353.797,3517.394,3540.237,3436.569,3418.067,3641.034,3708.478,3834.313,4123.956,4254.560,4821.917,4434.030,4174.454,3920.209,4106.851,4
7,7,chiapas,6052.549,6386.225,6231.334,4950.321,6006.764,6014.228,5982.459,5652.104,5624.642,5798.165,5361.347,5228.832,6077.716,5992.626,5977.213,5928.178,5
8,8,chihuahua,7612.652,8531.909,8293.606,8912.666,7609.848,8932.106,8063.444,8084.042,7724.338,7301.801,7298.381,6506.445,7980.328,7914.189,7702.155,7850.709,6
9,9,ciudad de mexico,60985.387,63419.472,63731.593,58169.971,56811.627,57284.316,48731.217,50686.539,53675.473,56257.256,53555.241,47248.377,52847.297,51743.994,50190.927,49267.264,7
5,5,coahuila,4785.095,5066.859,5088.358,5965.387,5986.460,6186.633,5382.830,5076.590,5263.023,5589.676,5555.012,4859.747,5676.806,6103.111,6077.479,6710.143,8
6,6,colima,3225.666,3185.748,3370.707,3498.966,3180.688,2869.044,3074.594,3081.683,3179.156,3222.677,2873.769,3391.065,3212.563,3365.592,3643.079,3353.747,9
10,10,durango,1962.652,1987.078,1982.342,2259.835,2236.939,2348.798,2320.742,2345.391,2173.036,2273.304,2088.836,2281.060,2430.076,2517.947,2561.084,2739.303,10
15,15,estado de mexico,18356.796,18073.754,17911.955,20479.487,22951.450,22932.405,19738.768,18544.260,20210.343,19844.652,18749.053,21273.834,18240.677,19557.847,20500.448,18985.857,11
11,11,guanajuato,9365.469,9274.084,9558.573,10029.810,9529.606,9229.498,8878.111,9332.835,9402.064,10362.758,10631.670,10835.898,11654.369,12317.274,13040.812,13334.502,12
13,13,guerrero,10441.662,13077.126,12579.139,12923.496,13733.286,14059.602,11869.067,12818.629,11162.587,11616.156,11368.497,12396.321,12928.744,13001.839,13590.524,15154.976,13
12,12,hidalgo,3582.343,3277.533,3115.424,2976.643,2946.893,2611.448,2108.660,2430.670,2851.879,3314.977,3399.248,3749.557,4358.911,4093.143,3939.656,4504.408,14
14,14,jalisco,23282.562,22163.198,23969.114,24658.656,24726.775,24842.627,23067.045,22724.650,23275.943,23997.350,25212.586,30059.885,28625.848,31007.461,32907.196,32924.853,15
16,16,michoacan,7477.540,7331.995,8951.234,7807.425,7415.091,7687.477,7648.239,7457.483,6745.784,6793.939,6363.175,6672.312,6158.453,6579.271,7218.142,7452.901,16
17,17,morelos,5545.121,5502.879,5178.247,6202.708,5568.332,5636.316,5063.571,4694.450,4429.124,4613.546,4724.162,4284.195,5175.928,5145.195,5362.678,6346.857,17
18,18,nayarit,7442.226,7734.155,9260.542,9977.811,7684.346,9330.366,8603.284,10144.167,9612.622,7516.852,9533.392,10369.598,13661.417,14519.415,15433.944,15443.417,18
19,19,nuevo leon,15772.058,15673.311,16271.320,16954.555,18567.970,17253.403,14558.709,13215.834,12515.142,14047.300,14763.572,16079.040,17424.305,18158.000,18574.956,19103.307,19
20,20,oaxaca,6352.153,6833.573,6843.696,6233.009,6323.959,6570.725,6597.347,6544.451,6843.724,6678.700,7206.284,7019.452,7730.045,7247.216,7787.547,8662.424,20
21,21,puebla,8037.292,7899.302,6506.905,6389.803,6274.178,6554.244,6298.040,6337.239,6562.144,7203.290,8389.824,9309.609,10057.675,9970.502,10339.914,11130.528,21
22,22,queretaro,4417.751,4604.826,4669.789,5153.362,5210.042,4902.690,4537.701,5054.769,5303.781,5675.607,6091.261,6346.086,6690.525,7577.610,7877.612,8029.432,22
23,23,quintana roo,32380.682,35181.012,32017.471,31804.810,41084.933,44227.868,37483.001,43510.115,45219.865,50529.431,52930.544,56043.540,60651.430,62407.021,64427.905,66084.735,23
24,24,san luis potosi,4706.504,5763.839,5302.651,5246.736,5506.387,5960.915,5154.130,4501.921,4721.922,4777.003,4673.879,3955.152,4935.355,5468.285,6042.984,6258.018,24
25,25,sinaloa,7823.521,7958.754,9925.138,10395.509,10123.523,10130.076,9918.678,9371.723,9066.516,8968.758,8864.609,9457.520,10341.243,10598.682,11069.010,10494.404,25
26,26,sonora,6902.357,7407.234,7766.069,9329.852,8619.016,7458.026,7231.783,6926.270,7455.681,7908.348,7449.531,7403.306,7863.344,8288.629,8599.101,8604.950,26
27,27,tabasco,5716.830,5923.131,5732.307,6360.371,5538.573,5588.850,5101.747,5004.653,5128.864,5931.322,5443.260,5112.467,5150.733,4800.688,4965.644,5249.435,27
28,28,tamaulipas,6559.963,6831.824,6499.536,6619.897,6701.126,6978.607,6387.353,4856.793,5613.150,6097.053,7483.509,5955.847,6445.791,6760.155,6561.370,7325.560,28
29,29,tlaxcala,2494.659,2907.019,2547.686,2734.577,1788.716,1481.318,1374.307,1314.086,1252.540,1285.599,1260.227,1254.076,1511.947,1516.073,1634.957,1427.076,29
30,30,veracruz,17981.905,16649.322,16003.211,17191.663,16060.765,13827.448,13439.748,12790.663,12377.503,12858.147,12725.118,13758.600,12283.502,11050.755,11043.539,11470.447,30
31,31,yucatan,4991.722,5290.800,5793.468,5445.108,5473.290,5669.843,4745.718,4960.058,5428.318,5390.157,5044.927,5089.341,5706.093,5555.322,5902.968,5759.519,31
32,32,zacatecas,1986.709,2078.808,2303.492,2404.632,2388.085,2415.604,2375.150,2416.801,2048.780,2156.416,2136.028,2196.989,2484.285,2614.324,2657.271,2747.637,32

In [9]:
#Let's turn to upper case all the names of the states
new_df['state'] = new_df['state'].str.upper() 
new_df

C:\anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,id,state,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,id_state
1,1,AGUASCALIENTES,3009.298,2846.622,2670.236,2449.527,2376.980,2605.283,2190.537,2307.857,2439.548,2817.615,2902.186,3013.849,3390.240,3669.932,3928.135,4396.160,1
2,2,BAJA CALIFORNIA,12204.779,12381.124,13254.712,13115.948,13091.387,11072.794,9984.990,9735.826,9929.754,10206.564,10893.632,11263.834,12024.583,12641.127,12643.593,11137.582,2
3,3,BAJA CALIFORNIA SUR,5821.453,7885.062,11014.099,13048.744,15306.901,13644.222,13294.530,13895.684,14250.285,15999.833,15543.510,14647.114,17284.922,18672.983,20919.630,23710.001,3
4,4,CAMPECHE,3540.521,3353.797,3517.394,3540.237,3436.569,3418.067,3641.034,3708.478,3834.313,4123.956,4254.560,4821.917,4434.030,4174.454,3920.209,4106.851,4
7,7,CHIAPAS,6052.549,6386.225,6231.334,4950.321,6006.764,6014.228,5982.459,5652.104,5624.642,5798.165,5361.347,5228.832,6077.716,5992.626,5977.213,5928.178,5
8,8,CHIHUAHUA,7612.652,8531.909,8293.606,8912.666,7609.848,8932.106,8063.444,8084.042,7724.338,7301.801,7298.381,6506.445,7980.328,7914.189,7702.155,7850.709,6
9,9,CIUDAD DE MEXICO,60985.387,63419.472,63731.593,58169.971,56811.627,57284.316,48731.217,50686.539,53675.473,56257.256,53555.241,47248.377,52847.297,51743.994,50190.927,49267.264,7
5,5,COAHUILA,4785.095,5066.859,5088.358,5965.387,5986.460,6186.633,5382.830,5076.590,5263.023,5589.676,5555.012,4859.747,5676.806,6103.111,6077.479,6710.143,8
6,6,COLIMA,3225.666,3185.748,3370.707,3498.966,3180.688,2869.044,3074.594,3081.683,3179.156,3222.677,2873.769,3391.065,3212.563,3365.592,3643.079,3353.747,9
10,10,DURANGO,1962.652,1987.078,1982.342,2259.835,2236.939,2348.798,2320.742,2345.391,2173.036,2273.304,2088.836,2281.060,2430.076,2517.947,2561.084,2739.303,10
15,15,ESTADO DE MEXICO,18356.796,18073.754,17911.955,20479.487,22951.450,22932.405,19738.768,18544.260,20210.343,19844.652,18749.053,21273.834,18240.677,19557.847,20500.448,18985.857,11
11,11,GUANAJUATO,9365.469,9274.084,9558.573,10029.810,9529.606,9229.498,8878.111,9332.835,9402.064,10362.758,10631.670,10835.898,11654.369,12317.274,13040.812,13334.502,12
13,13,GUERRERO,10441.662,13077.126,12579.139,12923.496,13733.286,14059.602,11869.067,12818.629,11162.587,11616.156,11368.497,12396.321,12928.744,13001.839,13590.524,15154.976,13
12,12,HIDALGO,3582.343,3277.533,3115.424,2976.643,2946.893,2611.448,2108.660,2430.670,2851.879,3314.977,3399.248,3749.557,4358.911,4093.143,3939.656,4504.408,14
14,14,JALISCO,23282.562,22163.198,23969.114,24658.656,24726.775,24842.627,23067.045,22724.650,23275.943,23997.350,25212.586,30059.885,28625.848,31007.461,32907.196,32924.853,15
16,16,MICHOACAN,7477.540,7331.995,8951.234,7807.425,7415.091,7687.477,7648.239,7457.483,6745.784,6793.939,6363.175,6672.312,6158.453,6579.271,7218.142,7452.901,16
17,17,MORELOS,5545.121,5502.879,5178.247,6202.708,5568.332,5636.316,5063.571,4694.450,4429.124,4613.546,4724.162,4284.195,5175.928,5145.195,5362.678,6346.857,17
18,18,NAYARIT,7442.226,7734.155,9260.542,9977.811,7684.346,9330.366,8603.284,10144.167,9612.622,7516.852,9533.392,10369.598,13661.417,14519.415,15433.944,15443.417,18
19,19,NUEVO LEON,15772.058,15673.311,16271.320,16954.555,18567.970,17253.403,14558.709,13215.834,12515.142,14047.300,14763.572,16079.040,17424.305,18158.000,18574.956,19103.307,19
20,20,OAXACA,6352.153,6833.573,6843.696,6233.009,6323.959,6570.725,6597.347,6544.451,6843.724,6678.700,7206.284,7019.452,7730.045,7247.216,7787.547,8662.424,20
21,21,PUEBLA,8037.292,7899.302,6506.905,6389.803,6274.178,6554.244,6298.040,6337.239,6562.144,7203.290,8389.824,9309.609,10057.675,9970.502,10339.914,11130.528,21
22,22,QUERETARO,4417.751,4604.826,4669.789,5153.362,5210.042,4902.690,4537.701,5054.769,5303.781,5675.607,6091.261,6346.086,6690.525,7577.610,7877.612,8029.432,22
23,23,QUINTANA ROO,32380.682,35181.012,32017.471,31804.810,41084.933,44227.868,37483.001,43510.115,45219.865,50529.431,52930.544,56043.540,60651.430,62407.021,64427.905,66084.735,23
24,24,SAN LUIS POTOSI,4706.504,5763.839,5302.651,5246.736,5506.387,5960.915,5154.130,4501.921,4721.922,4777.003,4673.879,3955.152,4935.355,5468.285,6042.984,6258.018,24
25,25,SINALOA,7823.521,7958.754,9925.138,10395.509,10123.523,10130.076,9918.678,9371.723,9066.516,8968.758,8864.609,9457.520,10341.243,10598.682,11069.010,10494.404,25
26,26,SONORA,6902.357,7407.234,7766.069,9329.852,8619.016,7458.026,7231.783,6926.270,7455.681,7908.348,7449.531,7403.306,7863.344,8288.629,8599.101,8604.950,26
27,27,TABASCO,5716.830,5923.131,5732.307,6360.371,5538.573,5588.850,5101.747,5004.653,5128.864,5931.322,5443.260,5112.467,5150.733,4800.688,4965.644,5249.435,27
28,28,TAMAULIPAS,6559.963,6831.824,6499.536,6619.897,6701.126,6978.607,6387.353,4856.793,5613.150,6097.053,7483.509,5955.847,6445.791,6760.155,6561.370,7325.560,28
29,29,TLAXCALA,2494.659,2907.019,2547.686,2734.577,1788.716,1481.318,1374.307,1314.086,1252.540,1285.599,1260.227,1254.076,1511.947,1516.073,1634.957,1427.076,29
30,30,VERACRUZ,17981.905,16649.322,16003.211,17191.663,16060.765,13827.448,13439.748,12790.663,12377.503,12858.147,12725.118,13758.600,12283.502,11050.755,11043.539,11470.447,30
31,31,YUCATAN,4991.722,5290.800,5793.468,5445.108,5473.290,5669.843,4745.718,4960.058,5428.318,5390.157,5044.927,5089.341,5706.093,5555.322,5902.968,5759.519,31
32,32,ZACATECAS,1986.709,2078.808,2303.492,2404.632,2388.085,2415.604,2375.150,2416.801,2048.780,2156.416,2136.028,2196.989,2484.285,2614.324,2657.271,2747.637,32

In [10]:
#Lets change the order of the df
#Create a list of year
years = [2003+i for i in range(16)]
print(years)

[2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]

In [11]:
#Lets create an empty df
gdp_df = pd.DataFrame(columns = ['id_state','states', 'tourism_gdp', 'year']) 
gdp_df

Empty DataFrame
Columns: [id_state, states, tourism_gdp, year]
Index: []

In [12]:
#Loop to rewrite the df
for year in years:
    syear = f"{year}"
    #Select the columns of interest as a list
    data = [new_df["id_state"], new_df["state"], new_df[year]]
    #Cretae the name of the columns
    headers = ['id_state','states', 'tourism_gdp',]
    #Coherce in a df
    aux = pd.concat(data, axis=1, keys=headers)
    #Add a column with the year 
    aux["year"] = [year] * 32
    #Concatenate in the empty df
    gdp_df = pd.concat([gdp_df, aux])

In [13]:
gdp_df.head()

  id_state               states  tourism_gdp  year
1        1       AGUASCALIENTES     3009.298  2003
2        2      BAJA CALIFORNIA    12204.779  2003
3        3  BAJA CALIFORNIA SUR     5821.453  2003
4        4             CAMPECHE     3540.521  2003
7        5              CHIAPAS     6052.549  2003

In [14]:
print(gdp_df.shape)

(512, 4)

In [15]:
gdp_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 512 entries, 1 to 32
Data columns (total 4 columns):
id_state       512 non-null object
states         512 non-null object
tourism_gdp    512 non-null float64
year           512 non-null object
dtypes: float64(1), object(3)
memory usage: 20.0+ KB

In [16]:
gdp_df['year'] = gdp_df['year'].astype(int)

In [17]:
gdp_df.to_csv('../data/gdp_tourism.csv', index = False)